version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: code_platform_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: leetradb
    volumes:
      - leetra-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  leetra-db-data:

